# Block-Shock method with complementary 2:4 masks.

method:
  name: block_shock_2gpu
  mode: semistructured
  tensor_parallel: sum_outputs
  recompress_each_step: false
  drop_full_weight: true
  validate_weight_2of4: false
